name: hello-world # name of this workflow
on: push # trigger the pipeline on a push event
jobs:
  hello-world-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository Code # name of this step
        uses: actions/checkout@v4
      - name: Print File Content
        run: echo "$(cat hello_world.txt)"
